name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run unit tests
        run: mvn test

      - name: Update README with test result badge
        if: always()
        run: |
          RESULT=${{ job.status }}
          BADGE_URL="https://img.shields.io/badge/tests-${RESULT}-brightgreen"
          sed -i.bak 's|!\[Build Status\](.*)|![Build Status]('"${BADGE_URL}"')|g' README.md

      - name: Commit README badge update
        if: always()
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with test result badge'
          git push https://ercankirbiyik:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:refs/heads/main

